### ISSUE TITLE
Create poll of interest in topics

### ISSUE THREAD

**Issue by switchspan** [GDGHamptonRoads/logistics#3]
Create poll of interest in topics - possibly Google Forms/Google Survey
Topics:

- Flutter/Dart
- PWA
- Kotlin/Android**
- TensorFlow
- Google Cloud
- Udacity?
- ML/AI APIs
- IoT
- Google actions

**Comment by switchspan** [comment]
http://forms.google.com/

**Comment by BenjaminEarley** [comment]
https://docs.google.com/forms/d/1BqwZoTplhfeFg64YHr7oca8hGsL2q_SPPPBo0gjGbqc/edit
